DROP TABLE USERS;
CREATE TABLE if not exists USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  email VARCHAR(250) DEFAULT NULL,
  password VARCHAR(250) DEFAULT NULL,
  provider ENUM('LOCAL', 'GOOGLE'),
  username VARCHAR(250) NOT NULL
);